apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::561162283399:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P1RZ3HMG884A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::561162283399:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-28T15:06:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "879"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 719a9c3b-3902-481b-932a-9af6cac3a17e
